version: 2

project_name: worky

builds:
  - id: worky
    main: ./cmd/worky
    binary: worky
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -X github.com/davideimola/worky/cmd/worky/cmd.Version={{ .Version }}

archives:
  - id: worky
    ids:
      - worky
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true
